CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE spicy_level_anchors (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     expression VARCHAR(100) NOT NULL,
                                     spicy_level VARCHAR(20) NOT NULL,
                                     embedding vector(1536) NOT NULL,
                                     created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                     CONSTRAINT uk_spicy_level_anchors_expression UNIQUE (expression)
);

CREATE INDEX idx_spicy_level_anchors_embedding
    ON spicy_level_anchors USING ivfflat (embedding vector_cosine_ops);