CREATE TABLE spicy_level_anchors (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     expression VARCHAR(100) NOT NULL,
                                     spicy_level VARCHAR(20) NOT NULL,
                                     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                     CONSTRAINT uk_spicy_level_anchors_expression UNIQUE (expression)
);