CREATE TABLE voice_correction_log (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       question_type VARCHAR(32) NOT NULL,
                                       recognized_text VARCHAR(200) NOT NULL,
                                       corrected_to VARCHAR(16) NOT NULL,
                                       created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
