package com.kiobridge.kiobridge.modules.spicylevel.service;

import java.util.List;
import java.util.Map;

public class SpicyLevelAnchorData {

    public static final List<Map.Entry<String, String>> ANCHORS = List.of(
        // HOT (매운맛)
        Map.entry("매운맛", "HOT"),
        Map.entry("매운 맛", "HOT"),
        Map.entry("불닭맛", "HOT"),
        Map.entry("불닭 맛", "HOT"),
        Map.entry("청양맛", "HOT"),
        Map.entry("청양 맛", "HOT"),
        Map.entry("화끈한맛", "HOT"),
        Map.entry("화끈한 맛", "HOT"),
        Map.entry("핵매운맛", "HOT"),
        Map.entry("핵매운 맛", "HOT"),
        Map.entry("아주매운맛", "HOT"),
        Map.entry("아주 매운 맛", "HOT"),
        Map.entry("엽떡맛", "HOT"),
        Map.entry("엽떡 맛", "HOT"),
        Map.entry("엽기떡볶이맛", "HOT"),
        Map.entry("엽기떡볶이 맛", "HOT"),
        Map.entry("존맛탱매운맛", "HOT"),
        Map.entry("존맛탱 매운 맛", "HOT"),
        Map.entry("눈물나게매운맛", "HOT"),
        Map.entry("눈물나게 매운 맛", "HOT"),
        Map.entry("불지옥맛", "HOT"),
        Map.entry("불지옥 맛", "HOT"),
        Map.entry("극한매운맛", "HOT"),
        Map.entry("극한 매운 맛", "HOT"),
        Map.entry("타는맛", "HOT"),
        Map.entry("타는 맛", "HOT"),

        // MEDIUM (중간맛)
        Map.entry("중간맛", "MEDIUM"),
        Map.entry("중간 맛", "MEDIUM"),
        Map.entry("보통맛", "MEDIUM"),
        Map.entry("보통 맛", "MEDIUM"),
        Map.entry("보통이요", "MEDIUM"),
        Map.entry("보통으로요", "MEDIUM"),
        Map.entry("그냥 보통", "MEDIUM"),
        Map.entry("약간매운맛", "MEDIUM"),
        Map.entry("약간 매운 맛", "MEDIUM"),
        Map.entry("적당히매운맛", "MEDIUM"),
        Map.entry("적당히 매운 맛", "MEDIUM"),
        Map.entry("얼큰한맛", "MEDIUM"),
        Map.entry("얼큰한 맛", "MEDIUM"),
        Map.entry("칼칼한맛", "MEDIUM"),
        Map.entry("칼칼한 맛", "MEDIUM"),
        Map.entry("적당히칼칼한맛", "MEDIUM"),
        Map.entry("적당히 칼칼한 맛", "MEDIUM"),
        Map.entry("은근매운맛", "MEDIUM"),
        Map.entry("은근 매운 맛", "MEDIUM"),

        // MILD (순한맛)
        Map.entry("순한맛", "MILD"),
        Map.entry("순한 맛", "MILD"),
        Map.entry("안매운맛", "MILD"),
        Map.entry("안 매운 맛", "MILD"),
        Map.entry("순함", "MILD"),
        Map.entry("담백한맛", "MILD"),
        Map.entry("담백한 맛", "MILD"),
        Map.entry("고소한맛", "MILD"),
        Map.entry("고소한 맛", "MILD"),
        Map.entry("짜지않은맛", "MILD"),
        Map.entry("짜지 않은 맛", "MILD"),
        Map.entry("슴슴한맛", "MILD"),
        Map.entry("슴슴한 맛", "MILD"),
        Map.entry("삼삼한맛", "MILD"),
        Map.entry("삼삼한 맛", "MILD"),
        Map.entry("자극적이지않은맛", "MILD"),
        Map.entry("자극적이지 않은 맛", "MILD"),
        Map.entry("아이도먹을수있는맛", "MILD"),
        Map.entry("아이도 먹을 수 있는 맛", "MILD"),
        Map.entry("연한맛", "MILD"),
        Map.entry("연한 맛", "MILD"),
        Map.entry("부드러운맛", "MILD"),
        Map.entry("부드러운 맛", "MILD"),
        Map.entry("자극없는맛", "MILD"),
        Map.entry("자극 없는 맛", "MILD"),
        Map.entry("아기용맛", "MILD"),
        Map.entry("아기용 맛", "MILD"),

        // NO_PREFERENCE (상관없음)
        Map.entry("아무거나", "NO_PREFERENCE"),
        Map.entry("아무 거나", "NO_PREFERENCE"),
        Map.entry("상관없어요", "NO_PREFERENCE"),
        Map.entry("아무 맛이나", "NO_PREFERENCE"),
        Map.entry("다 좋아요", "NO_PREFERENCE"),
        Map.entry("전부 괜찮아요", "NO_PREFERENCE")
    );
}